<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CodeBrix.Platform.GameEngine.MitLicenseForever" Version="1.0.275.9000-split.1" />
    <PackageReference Include="CodeBrix.Platform.GameEngine.KenneyAssets.MitLicenseForever" Version="1.0.275.9000-split.1" />
  </ItemGroup>
</Project>
