<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../../../PlayTestSupport/CodeBrix.Sample.PlayTests.props" />
  <PropertyGroup>
    <RootNamespace>KenneyAssetBrowser.PlayTests</RootNamespace>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>
  <Import Project="../../src/KenneyAssetBrowser.UI/KenneyAssetBrowser.UI.projitems" Label="Shared" />
  <ItemGroup>
    <PackageReference Include="CodeBrix.Platform.PlayTest.OpenGL.ApacheLicenseForever" Version="1.0.281.314" />
    <PackageReference Include="SilverAssertions.ApacheLicenseForever" Version="1.0.248.1071" />
    <ProjectReference Include="../../src/KenneyAssetBrowser.Core/KenneyAssetBrowser.Core.csproj" />
  </ItemGroup>
</Project>
