<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../../../PlayTestSupport/CodeBrix.Sample.PlayTests.props" />
  <PropertyGroup>
    <RootNamespace>SimpleCbxVideoPlayer.PlayTests</RootNamespace>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>
  <Import Project="../../src/SimpleCbxVideoPlayer.UI/SimpleCbxVideoPlayer.UI.projitems" Label="Shared" />
  <ItemGroup>
    <PackageReference Include="CodeBrix.Platform.PlayTest.OpenGL.ApacheLicenseForever" Version="1.0.280.1176" />
    <PackageReference Include="SilverAssertions.ApacheLicenseForever" Version="1.0.248.1071" />
    <ProjectReference Include="../../src/SimpleCbxVideoPlayer.Core/SimpleCbxVideoPlayer.Core.csproj" />
  </ItemGroup>
</Project>
