<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../../../PlayTestSupport/CodeBrix.Sample.PlayTests.props" />
  <PropertyGroup>
    <RootNamespace>GameEngineMusicDemo.PlayTests</RootNamespace>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>
  <Import Project="../../src/GameEngineMusicDemo.UI/GameEngineMusicDemo.UI.projitems" Label="Shared" />
  <ItemGroup>
    <PackageReference Include="SilverAssertions.ApacheLicenseForever" Version="1.0.248.1071" />
    <ProjectReference Include="../../src/GameEngineMusicDemo.Core/GameEngineMusicDemo.Core.csproj" />
  </ItemGroup>
</Project>
