using CodeBrix.PdfDocuments.Drawing;
using CodeBrix.PdfDocuments.Pdf;
using PolyHavenBrowser.CreateDocument.Internal;

namespace PolyHavenBrowser.CreateDocument;

/// <summary>
/// Creates the glossy marketing one-sheet PDF for a downloaded Poly Haven model. The
/// caller gathers everything into a <see cref="MarketingSheetRequest"/> (display texts,
/// facts, the catalog thumbnail, and the rendered product shots); this type samples the
/// per-model accent color, lays out the poster, and writes a single-page US Letter PDF.
/// </summary>
public sealed class MarketingSheetCreator
{
    /// <summary>Creates the one-sheet and writes it to <paramref name="outputPath"/>.</summary>
    public void CreateToFile(MarketingSheetRequest request, string outputPath)
    {
        ArgumentNullException.ThrowIfNull(request);
        if (string.IsNullOrWhiteSpace(outputPath))
        {
            throw new ArgumentException("An output path is required.", nameof(outputPath));
        }

        using var document = Compose(request);
        document.Save(outputPath);
    }

    /// <summary>Creates the one-sheet and returns the PDF bytes (used by tests and previews).</summary>
    public byte[] CreateToBytes(MarketingSheetRequest request)
    {
        ArgumentNullException.ThrowIfNull(request);

        using var document = Compose(request);
        using var stream = new MemoryStream();
        document.Save(stream, closeStream: false);
        return stream.ToArray();
    }

    private static PdfDocument Compose(MarketingSheetRequest request)
    {
        SheetFonts.EnsureRegistered();

        var document = new PdfDocument();
        document.Info.Title = $"{request.ModelName} — Poly Haven model one-sheet";
        document.Info.Subject = "A marketing one-sheet generated by PolyHavenBrowser";

        var page = document.AddPage();
        page.Width = SheetTheme.PageWidth;
        page.Height = SheetTheme.PageHeight;

        var accent = AccentColorSampler.Sample(request.CatalogThumbnailBytes);
        var theme = new SheetTheme(accent);

        using var gfx = XGraphics.FromPdfPage(page);
        new SheetComposer(request, theme).Compose(gfx);

        return document;
    }
}
